version: '3.8'

services:
  # Reverse Proxy (nginx)
  proxy:
    image: nginx:alpine
    container_name: aiquizmaker-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web
    networks:
      - aiquizmaker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      timeout: 5s
      retries: 5

  # Backend API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: aiquizmaker-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MAX_PDF_SIZE=${MAX_PDF_SIZE:-104857600}
      - MAX_PAGES_PER_PDF=${MAX_PAGES_PER_PDF:-200}
      - DEFAULT_QUESTIONS_PER_PAGE=${DEFAULT_QUESTIONS_PER_PAGE:-2}
      - WEB_URL=${WEB_URL:-http://localhost:8000}
    volumes:
      - api_uploads:/app/uploads
      - api_storage:/app/quiz-storage
    networks:
      - aiquizmaker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/config"]
      timeout: 5s
      retries: 5

  # Frontend Web Service  
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - API_URL=${API_URL:-http://localhost:8000/api}
    container_name: aiquizmaker-web
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - API_URL=${API_URL:-http://localhost:8000/api}
    depends_on:
      - api
    networks:
      - aiquizmaker-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      timeout: 5s
      retries: 5

volumes:
  api_uploads:
    driver: local
  api_storage:
    driver: local

networks:
  aiquizmaker-network:
    driver: bridge 